interface ExportStep {
  action: string
  target: string
  value?: string
  narration: string
}

export function generatePlaywrightCode(
  targetUrl: string,
  prompt: string,
  steps: ExportStep[]
): string {
  const lines: string[] = []

  lines.push(`import { test, expect } from '@playwright/test';`)
  lines.push('')
  lines.push(`// Auto-generated by AutoQA from: "${escapeStr(prompt)}"`)
  lines.push(`test('${escapeStr(prompt.slice(0, 80))}', async ({ page }) => {`)
  lines.push(`  await page.goto('${escapeStr(targetUrl)}');`)
  lines.push('')

  for (const step of steps) {
    if (step.action === 'done') break

    lines.push(`  // ${step.narration}`)

    switch (step.action) {
      case 'click':
        lines.push(`  await page.getByText('${escapeStr(step.target)}').click();`)
        break
      case 'type':
        lines.push(`  await page.getByText('${escapeStr(step.target)}').click();`)
        lines.push(`  await page.keyboard.type('${escapeStr(step.value || '')}');`)
        break
      case 'pressKey':
        lines.push(`  await page.keyboard.press('${escapeStr(step.value || 'Enter')}');`)
        break
      case 'scroll':
        lines.push(`  await page.mouse.wheel(0, ${step.value === 'up' ? -300 : 300});`)
        break
      case 'navigate':
        lines.push(`  await page.goto('${escapeStr(step.value || step.target)}');`)
        break
      case 'wait':
        lines.push(`  await page.waitForTimeout(${parseInt(step.value || '1000', 10)});`)
        break
      case 'hover':
        lines.push(`  await page.getByText('${escapeStr(step.target)}').hover();`)
        break
      default:
        lines.push(`  // Unknown action: ${step.action}`)
    }

    lines.push('')
  }

  lines.push(`});`)
  lines.push('')

  return lines.join('\n')
}

function escapeStr(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')
}
